-- AlterTable
ALTER TABLE `milestone` ADD COLUMN `rejection_reason` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('PENDING_ADMIN_UPLOAD', 'PENDING_CLIENT_APPROVAL', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING_ADMIN_UPLOAD';
