# .github/workflows/deploy.yml
name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to cPanel & Run Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # 1. Activate the Node.js Virtual Environment
            # This is the most important step to set up the correct PATH
            source /home/${{ secrets.USERNAME }}/nodevenv/api.digitalmarketingagency.ng/22/bin/activate

            # 2. Navigate to the correct application directory
            cd /home/${{ secrets.USERNAME }}/api.digitalmarketingagency.ng

            # 3. Pull the latest code from the main branch
            echo "--- Pulling latest code ---"
            git pull origin main

            # 4. Install/update production dependencies
            # These commands will now work because the environment is activated
            echo "--- Installing dependencies ---"
            npm install --production

            # 5. Run database migrations
            echo "--- Running database migrations ---"
            npx prisma migrate deploy

            # 6. Restart the app using the simple and reliable touch method
            echo "--- Sending restart signal to application ---"
            mkdir -p tmp
            touch tmp/restart.txt

            echo "--- Deployment script finished ---"
