# .github/workflows/deploy.yml
name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to cPanel & Run Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # 1. Activate the Node.js Virtual Environment for npm and npx
            source /home/${{ secrets.USERNAME }}/nodevenv/api.digitalmarketingagency.ng/22/bin/activate

            # 2. Define the full path to passenger-config
            export PASSENGER_CONFIG_PATH="/opt/cpanel/ea-ruby27/root/usr/bin/passenger-config"

            # 3. Navigate to the application directory
            cd /home/${{ secrets.USERNAME }}/api.digitalmarketingagency.ng

            # 4. Pull the latest code
            echo "--- Pulling latest code ---"
            git pull origin main

            # 5. Install dependencies
            echo "--- Installing dependencies ---"
            npm install --production

            # 6. Run database migrations
            echo "--- Running database migrations ---"
            npx prisma migrate deploy

            # --- 7. THE FINAL, CORRECT RESTART COMMAND ---
            echo "--- Force-restarting application to clear cache ---"

            # Use the correct `restart-app` command, run within the Ruby environment.
            # This single command replaces both the stop and start commands.
            scl enable ea-ruby27 "$PASSENGER_CONFIG_PATH restart-app $(pwd) --ignore-app-not-running"

            echo "--- Deployment script finished successfully ---"
